Forum/Models/HomeViewModel.cs
using Forum.Models.PostViewModels;
using System.Collections.Generic;

namespace Forum.Models
{
    public class HomeViewModel
    {
        public int NumberCreatedPosts { get; set; }
        public int NumberUsers { get; set; }
        public IEnumerable<PostResponseViewModel> latestPostsViewModel { get; set; }
        public IEnumerable<PostResponseViewModel> topMostCommentedPostsViewModel { get; set; }
    }
}

Forum/Controllers/AuthController.cs
using System;
using System.Threading.Tasks;

using Forum.Exceptions;
using Forum.Helpers;
using Forum.Models;
using Forum.Models.Contracts;
using Forum.Services.Exceptions;
using Forum.Services.Forum.Services.Contracts;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Forum.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService userService;
        private readonly IAuthenticationHelper authHelper;
        private readonly IRequestModelMapper modelMapper;
        private readonly IResponseViewModelMapper responseModelMapper;
        public AuthController(IUserService userService, IAuthenticationHelper authHelper, IRequestModelMapper modelMapper, IResponseViewModelMapper responseModelMapper)
        {
            this.userService = userService;
            this.authHelper = authHelper;
            this.modelMapper = modelMapper;
            this.responseModelMapper = responseModelMapper;
        }

        //GET: /auth/login
        public IActionResult Login()
        {
            var loginViewModel = new LoginViewModel();

            return this.View(loginViewModel);
        }

        //POST: /auth/login
        [HttpPost]
        public async Task<IActionResult> Login([Bind("Email, Password")] LoginViewModel loginViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(loginViewModel);
            }

            try
            {
                var role = HttpContext.Session.GetString("Role");
                var user = await this.authHelper.TryGetUser(loginViewModel.Email, loginViewModel.Password);
                this.HttpContext.Session.SetInt32("CurrentUserId", user.Id);
                this.HttpContext.Session.SetString("CurrentUser", user.Username);
                this.HttpContext.Session.SetString("CurrentUserEmail", user.Email);
                this.HttpContext.Session.SetString("CurrentUserPassword", user.Password);
                this.HttpContext.Session.SetString("Role", user.Role);
                
                return this.RedirectToAction("Index", "Home");
            }
            catch (AuthenticationException ex)
            {
                this.ModelState.AddModelError("Password", ex.Message);
                return this.View(loginViewModel);
            }
            catch (EntityNotFoundException ex)
            {
                this.ModelState.AddModelError("Email", ex.Message);
                return this.View(loginViewModel);
            }

        }

        //GET: /auth/logout
        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove("CurrentUser");
            this.HttpContext.Session.Remove("Role");
            this.HttpContext.Session.Remove("CurrentUserId");
            this.HttpContext.Session.Remove("CurrentUserEmail");
            this.HttpContext.Session.Remove("CurrentUserPassword");

            return this.RedirectToAction("Index", "Home");
        }

        //GET: /auth/register
        public IActionResult Register()
        {
            var registerViewModel = new RegisterViewModel();

            return this.View(registerViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Register([Bind("Username, Password, ConfirmPassword, Email, DisplayName")] RegisterViewModel registerViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(registerViewModel);
            }

            var userExists = await this.userService.ExistUserWithEmailAsync(registerViewModel.Email);
            if (userExists)
            {
                this.ModelState.AddModelError("Email", "User with same email already exists.");
                return this.View(registerViewModel);
            }

             userExists = await this.userService.ExistUserWithUsernameAsync(registerViewModel.Username);
            if (userExists)
            {
                this.ModelState.AddModelError("Usernme", "User with same username already exists.");
                return this.View(registerViewModel);
            }
            if (!registerViewModel.Password.Equals(registerViewModel.ConfirmPassword))
            {
                this.ModelState.AddModelError("ConfirmPassword", "Confirm password should match password.");
                return this.View(registerViewModel);
            }

            var user = this.modelMapper.ToUserRequestDto(registerViewModel);
            var userRegistration = await this.userService.RegisterAsync(user);
            var userRegistrationViewModel = this.responseModelMapper.UserRegistrationViewModel(userRegistration);
            
                return this.View("RegistrationVerification", userRegistrationViewModel);
        }
       
        public async Task<IActionResult> ActivateAccount([FromQuery] string userId, [FromQuery] string activationCode)
        {
            if (userId == null || activationCode == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            try
            {
                var message = await this.userService.ActivateAccountAsync(int.Parse(userId), activationCode);
                var activationViewModel = new ActivationViewModel
                {
                    Message = message
                };

                return this.View(activationViewModel);
            }
            catch (UnauthorizedAccessException)
            {
                ViewBag.ErrorMessage = "Invalid user.";
                return this.View("NotFound");
            }
        }        
    }
}

Forum/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Forum.Models;
using Forum.Models.Contracts;
using Forum.Services.Forum.Services.Contracts;

using Microsoft.AspNetCore.Mvc;

namespace Forum.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly IResponseViewModelMapper responseViewModelMapper;

        public HomeController(IPostService postService, IUserService userService, IResponseViewModelMapper responseViewModelMapper)
        {
            this.postService = postService;
            this.userService = userService;
            this.responseViewModelMapper = responseViewModelMapper;
        }

        public async Task<IActionResult> Index()
        {
            var usersCount = await this.userService.GetUsersCountAsync();
            var postCount = await this.postService.CountPosts();
            var topMostCommentedPostsDtos = await this.postService.GetMostPopularPostsAsync(10);
            var topMostCommentedPostsViewModels = 
                topMostCommentedPostsDtos.Select(p => this.responseViewModelMapper.ToPostResponseViewModel(p));

            var latestPosts = await this.postService.GetLatestPostsAsync(10);
            var latestPostsViewModel = 
                latestPosts.Select(p => this.responseViewModelMapper.ToPostResponseViewModel(p));

            var homeViewModel = new HomeViewModel
            {
                NumberUsers = usersCount,
                NumberCreatedPosts = postCount,
                latestPostsViewModel = latestPostsViewModel,
                topMostCommentedPostsViewModel = topMostCommentedPostsViewModels
            };

            return View(homeViewModel);
        }

        public IActionResult LearnMore()
        {
            return View();
        }

        public IActionResult ContactUs()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Forum/Controllers/PostsController.cs
using System.Threading.Tasks;

using Forum.Models;
using Forum.Services.Forum.Services.Contracts;

using Microsoft.AspNetCore.Mvc;

namespace Forum.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostService postService;
        public PostsController(IPostService postService)
        {
            this.postService = postService;
        }
        public IActionResult Index()
        {
            return this.View();
        }

        public async Task<IActionResult> Post(int id)
        {
            var post = await postService.GetPostAsync(id);
            var postViewModel = new PostViewModel(post);
            postViewModel.Likes = postService.GetPostLikes(id);
            return this.View(postViewModel);
        }
    }
}

Forum/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using Forum.Helpers;
using Forum.Models;
using Forum.Models.Contracts;
using Forum.Models.UserViewModels;

using Microsoft.AspNetCore.Mvc;
using Forum.Services.Forum.Services.Contracts;
using Microsoft.AspNetCore.Hosting;


namespace Forum.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IAuthenticationHelper authHelper;
        private readonly IWebHostEnvironment environment;
        private readonly IRequestModelMapper requestModelMapper;
        private readonly IResponseViewModelMapper responseModelMapper;

        public UserController(IUserService userService, IAuthenticationHelper authHelper, IWebHostEnvironment environment, IRequestModelMapper mapper, IResponseViewModelMapper responseModelMapper)
        {
            this.userService = userService;
            this.authHelper = authHelper;
            this.environment = environment;
            this.requestModelMapper = mapper;
            this.responseModelMapper = responseModelMapper;
        }

        public async Task<IActionResult> Index(int id)
        {
            if (!this.HttpContext.Session.Keys.Contains("CurrentUser"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            var user = await userService.GetUserByIdAsync(id);

            var viewModel = new UserViewModel
            {
                UserId = user.Id,
                Username = user.Username,
                Email = user.Email,
                Role = user.Role,
                DisplayName = user.DisplayName,
                MemberSince = user.MemberSince,
                Rating = user.Rating,
                ProfileImagePath = user.ProfileImageUrl,
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult>  ProfilePicture(UserUpdateProfilePictureModel updateProfilePictureModel)
        {
            if (!this.HttpContext.Session.Keys.Contains("CurrentUser"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            try
            {
                int id = updateProfilePictureModel.UserId;
                var user = await this.userService.GetUserMinAsync(updateProfilePictureModel.UserId);

                var extension = Path.GetExtension(updateProfilePictureModel.Image.FileName).TrimStart('.');
                var physicalPath = $"{environment.WebRootPath}\\profileImages";
                var updatePictureRequestDto = this.requestModelMapper.ToUserUpdateProfilePictureRequestDto(updateProfilePictureModel);
                await this.userService.UpdateProfileImageAsync(updateProfilePictureModel.UserId, updatePictureRequestDto, physicalPath, extension);

                return RedirectToAction("Index", new { id = updateProfilePictureModel.UserId });
            }
            catch (Exception ex)
            {
                 return RedirectToAction("Index", updateProfilePictureModel.UserId);
            }
        }

        [HttpGet]
        //[AuthorizationAttribute(Role = "Admin")]
        public IActionResult ShowUsers()
        {
            if (!this.HttpContext.Session.Keys.Contains("CurrentUser"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            return this.View();
        }

        [HttpPost]
        // [AuthorizationAttribute(Role = "Admin")]
        public async Task<IActionResult> ShowUsersPagination([FromBody] PaginationViewModel model)
        {
            if (!this.HttpContext.Session.Keys.Contains("CurrentUser"))
            {
                return this.RedirectToAction("Login", "Auth");
            }

            int? rating = null;
            bool ratingInteger = int.TryParse(model.Rating, out int ratingInt);
            if (ratingInteger)
            {
                rating = ratingInt;
            }

            var usersPaginationResponse =
                await this.userService.GetAllPaginationAsync(model.Skip, model.Take, rating, model.SortType, model.Direction, model.UserStatus, model.SearchValue);
            var usersListResponseModel = new List<UserResponseViewModel>();
            foreach (var userDto in usersPaginationResponse.Items)
            {
                var userResponseViewModel = this.responseModelMapper.ToUserResponseViewModel(userDto);
                usersListResponseModel.Add(userResponseViewModel);
            }

            var usersListViewModel = new UsersListResponseViewModel
            {
                UsersList = usersListResponseModel,
                PageNumber = model.PageNumber,
                ItemsCount = usersPaginationResponse.TotalItemsCount,
                ItemsPerPage = model.Take
            };

            return this.PartialView("_UsersTablePartial", usersListViewModel);
        }

        [HttpGet]
        [AuthorizationAttribute(Role = "Admin")]
        public async Task<IActionResult> BlockUser(int id)
        {
            try
            {
                if (!this.HttpContext.Session.Keys.Contains("CurrentUser"))
                {
                    return this.RedirectToAction("Login", "Auth");
                }

                var userDto = await this.userService.GetUserByIdAsync(id);
                var userViewModel = this.responseModelMapper.ToUserResponseViewModel(userDto);

                return this.View(userViewModel);
            }
            catch (Exception)
            {
                return this.RedirectToAction(nameof(this.ShowUsers));
            }

        }

        [HttpGet]
        [AuthorizationAttribute(Role = "Admin")]
        public async Task<IActionResult> BlockUserConfirmation(int id)
        {
            try
            {
                var blocked = await this.userService.BlockUser(id);

                return this.View("ShowUsers");
            }
            catch (Exception)
            {
                return this.RedirectToAction(nameof(this.ShowUsers));
            }

        }

        [HttpGet]
        [AuthorizationAttribute(Role = "Admin")]
        public async Task<IActionResult> UnblockUser(int id)
        {
            try
            {
                var unblocked = await this.userService.UnblockUser(id);

                return this.View("ShowUsers");
            }
            catch (Exception)
            {

                return this.RedirectToAction(nameof(this.ShowUsers));
            }

        }
    }
}

Forum/Views/Home/ContactUs.cshtml
<style>
    #email-style {
        color: blue;
        text-align: center;
    }
    #contact-us-content {
        margin-top: 30px;
        margin-bottom: 30px;
        text-align: center;
        font-size: large;
    }
    #contact-us-header {
        margin-top: 30px;
        text-align: center;
    }

</style>

<section id="banner">
    <h2>Contact Us</h2>
    <p>Tell us what you think about our forum.</p>
</section>
<section id="main" class="container medium">
    <div class="box">
        <h4 id="contact-us-header">If you have any questions, please, do not hesitate do contact us.</h4>
        <p id="contact-us-content">You can find us on email: <p id="email-style">shareideas.forum2021@gmail.com </p></p>
        <div class="col-12">
            <ul class="actions special">
                <li><a asp-action="Index" class="btn btn-secondary">Back</a></li>
            </ul>
        </div>
    </div>
</section>

Forum/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http;
@model Forum.Models.HomeViewModel
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.Get("CurrentUser");
    this.ViewData["Role"] = this.Context.Session.GetString("Role");
    this.ViewData["UserId"] = this.Context.Session.GetInt32("CurrentUserId");
    ViewData["Title"] = "Home Page";
}

<!-- Banner -->
<section id="banner">
    <h2>The Software Lab</h2>
    <p>The Forum for everything you need!</p>
    <ul class="actions special">
        @{
            if (!(bool)this.ViewData["IsAuthenticated"])
            {
                <li><a asp-controller="Auth" asp-action="Login" class="button primary">Sign In</a></li>
            }
            else
            {
                <li><a asp-controller="User" asp-action="Index" asp-route-id="@this.ViewData["UserId"]" class="button primary">Profile</a></li>
            }
        }
        <li><a asp-controller="Posts" asp-action="Index" class="button">Posts</a></li>
    </ul>
</section>

<section id="main" class="container">

    <section class="box special">
        <header class="major">
            <h2>
                Forum for sharing software tips and tricks
            </h2>
            <p style="margin-bottom: 40px; font-weight: bold">
                Here are some of our recent posts and <br />
                some of the most popular ones.
            </p>
        </header>
    </section>
        <div style="display:flex" >
            <div class="forum-container fill-container">
                <p style="text-align: center; font-size: x-large; font-weight: bold; font-style: inherit; margin-bottom: 30px">The Software Lab's popular posts:</p>

                @{
                    @foreach (var post in Model.topMostCommentedPostsViewModel)
                    {

                        <div class="forum-item">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="forum-icon">
                                        <i class="fa fa-comments" aria-hidden="true"></i>
                                    </div>
                                    <a href="/Posts/Post/@post.Id" class="forum-item-title">@post.Title</a>
                                    <div class="forum-sub-title">@post.Content </div>
                                </div>
                            </div>
                        </div>
                    }
                }

            </div>

            <div class="forum-container fill-container">
                <p style="text-align: center; font-size: x-large; font-weight: bold; font-style: inherit; margin-bottom: 30px">The Software Lab's latest posts:</p>

                @{
                    @foreach (var post in Model.latestPostsViewModel)
                    {

                        <div class="forum-item">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="forum-icon">
                                        <i class="fa fa-comments" aria-hidden="true"></i>
                                    </div>
                                    <a href="/Posts/Post/@post.Id" class="forum-item-title">@post.Title</a>
                                    <div class="forum-sub-title">@post.Content </div>
                                </div>
                            </div>
                        </div>

                    }
                }
            </div>

        </div>
  

    <section class="box special features">
        <div class="features-row">
            <section>
                <span class="icon solid major fa-users accent3"></span>
                <h3>Forum users: @Model.NumberUsers</h3>
            </section>
            <section>
                <span class="icon solid major fa-comments accent4"></span>
                <h3>Created posts: @Model.NumberCreatedPosts</h3>
            </section>
        </div>
    </section>
    <section class="box special features">
        <div class="features-row">
            <section>
                <span class="icon solid major fa-bolt accent2"></span>
                <h3>Forum rules</h3>
                <p>
                    Please be considerate in language you use on the forum, some of our members are younger than
                    others. Swearing is not completely banned, just do not swear unnecessarily, and only use
                    minor words. A filter is in place to safeguard this system.
                </p>
            </section>
            <section>
                <span class="icon solid major fa-ban accent5"></span>
                <h3>Insulting</h3>
                <p> Insulting and flaming or personal attacks against forum staff will be not tolerated.</p>
            </section>
        </div>
    </section>
</section>

Forum/Views/Home/LearnMore.cshtml
<section id="banner">
    <h2>BG-Tatko</h2>
    <p>The Forum for everything!</p>
</section>
<section id="main" class="container">

    <div class="box">
        <span class="image featured"><img src="images/pic01.jpg" alt="" /></span>
        <h3>Internet forum</h3>
        <p>
            An Internet forum, or message board, is an online discussion site where people can hold conversations in the form of posted messages. They differ from chat rooms in that
            messages are often longer than one line of text, and are at least temporarily archived. Also, depending on the access level of a user or the forum set-up, a posted message
            might need to be approved by a moderator before it becomes publicly visible.
        </p>
        <div class="row">
            <div class="row-6 row-12-mobilep">
                <h3>Topic</h3>
                <p>
                    Forums have a specific set of jargon associated with them; example: a single conversation is called a "thread", or topic.
                </p>
            </div>
        </div>
    </div>
</section>